/**
 * 50 exercises
 */
export const exercisesNames: string[] = [
  'Ring Row',
  'Ring Dips',
  'Tire Flip',
  'Tire Jump',
  'Ring L Sit',
  'Ring Plank',
  'Tire Carry',
  'Bar Chin Up',
  'Bar Pull Up',
  'Macebell 360',
  'Ring Chin Up',
  'Ring Maltese',
  'Ring Pull Up',
  'Ring Push Up',
  'Slider Pike ',
  'Tire Step Up',
  'Bar Dead Hang',
  'Barbell Climb',
  'Barbell Shrug',
  'Clubbell Mill',
  'Macebell Mill',
  'Plate Otis Up',
  'Bar L Sit Hang',
  'Clubbell Clean',
  'Clubbell Swing',
  'Plate Dead Bug',
  'Ring Chest Fly',
  'Ring Dead Hang',
  'Ring Handstand',
  'Tire Leg Press',
  'Trap Bar Shrug',
  'Wall Ball Toss',
  'Barbell Z Press',
  'Bodyweight Dips',
  'Bodyweight V Up',
  'Cable Face Pull',
  'Ring Archer Row',
  'Ring Iron Cross',
  'Ring L Sit Dips',
  'Ring L Sit Hang',
  'Ring Side Plank',
  'Ring Tuck L Sit',
  'Suspension Pike',
  'Tire Broad Jump',
  'Bar Skin the Cat',
  'Barbell Thruster',
  'Battle Rope Clap',
  'Bodyweight L Sit',
  'Bodyweight Squat',
  'Dumbbell Otis Up',
];

/**
 * 10 programs
 */
export const programsNames: string[] = [
  'Endurance Training Pogram',
  'Strength Training Pogram',
  'Core strength Training Pogram',
  'Bodybuilding Training Program',
  'Weight Training Program',
  'Marathon Training Program',
  'Power Training Pogram',
  'High Intensity Training Pogram',
  'Yoga',
  'Pilates',
];

/**
 * 25 first names
 */
export const userFirstNames: string[] = [
  'Josephine',
  'Aaron',
  'Oscar',
  'Kenneth',
  'Alfred',
  'Cecelia',
  'Rosetta',
  'Bess',
  'Jack',
  'Dylan',
  'Dollie',
  'Lawrence',
  'Leroy',
  'Lucille',
  'Raymond',
  'Lora',
  'Cornelia',
  'Sadie',
  'Gary',
  'Richard',
  'Jessie',
  'Lee',
  'Louisa',
  'Ola',
  'Ricardo',
];

/**
 * 25 random last names
 */
export const userLastNames: string[] = [
  'Allison',
  'Anderson',
  'Barnett',
  'Brooks',
  'Burns',
  'Clarke',
  'Colon',
  'Conner',
  'Dunn',
  'Edwards',
  'Frazier',
  'Gray',
  'Greer',
  'Griffith',
  'Harvey',
  'Hunter',
  'Love',
  'Marshall',
  'Matthews',
  'Mitchell',
  'Ramirez',
  'Rowe',
  'Ryan',
  'Stanley',
  'Young',
];
